### ISSUE TITLE
core.model_utils has no PPGN

### ISSUE THREAD

**Issue by Xenadon** [Jo3690/SOG#1]
I tried the training process using the command `python -m absorption.py model.num_layers 5 model.mini_layers 3 train.epochs 100` as in README, however it reports that 
```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 112, in _get_module_details
  File "/home/wt/SOG/SOG/SubOptGraph/absorption.py", line 7, in <module>
    from core.changed_model import GNNAsKernel
  File "/home/wt/SOG/SOG/SubOptGraph/../core/changed_model.py", line 7, in <module>
    from core.model_utils.ppgn import PPGN
ModuleNotFoundError: No module named 'core.model_utils.ppgn'
```

**Comment by Jo3690** [comment]
Hello, I've delete the irrelevant codes in the script including PPGN, you can check it in the latest version or delete them by yourself.

**Comment by Jo3690** [comment]
> I tried the training process using the command `python -m absorption.py model.num_layers 5 model.mini_layers 3 train.epochs 100` as in README, however it reports that
> 
> ```
> Traceback (most recent call last):
>   File "<frozen runpy>", line 189, in _run_module_as_main
>   File "<frozen runpy>", line 112, in _get_module_details
>   File "/home/wt/SOG/SOG/SubOptGraph/absorption.py", line 7, in <module>
>     from core.changed_model import GNNAsKernel
>   File "/home/wt/SOG/SOG/SubOptGraph/../core/changed_model.py", line 7, in <module>
>     from core.model_utils.ppgn import PPGN
> ModuleNotFoundError: No module named 'core.model_utils.ppgn'
> ```
Hello, I've deleted the irrelevant codes in the script including PPGN, you can check it in the latest version or delete them by yourself.

**Comment by Xenadon** [comment]
OK, that works! Thank you so much.

**Comment by Jo3690** [comment]
> OK, that works! Thank you so much.

Great, got it!
