### ISSUE TITLE
SubOptGraph /absorption.py line 177, self.collate has an error

### ISSUE THREAD

**Issue by BlackBoxOP** [Jo3690/SOG#2]
I tried the training process using the command python -m absorption.py model.num_layers 5 model.mini_layers 3 train.epochs 100 as in README, however it reports that
```
File "/home/user/repo/SOG/SubOptGraph/absorption.py", line 178, in process 
    torch.save(self.collate(data_list),
File "/home/user/anaconda3/envs/SOG/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 103, in collate
    data, slices, _ = collate(
File "/home/user/anaconda3/envs/SOG/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 84, in collate
    value, slices, incs = _collate(attr, values, data_list, stores,
File "/home/user/anaconda3/envs/SOG/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 155, in _collate
    value = torch.cat(values, dim=cat_dim or 0, out=out)
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 106 but got size 102 for tensor number 1 in the list.
```

**Comment by Jo3690** [comment]
> I tried the training process using the command python -m absorption.py model.num_layers 5 model.mini_layers 3 train.epochs 100 as in README, however it reports that
> 
> ```
> File "/home/user/repo/SOG/SubOptGraph/absorption.py", line 178, in process 
>     torch.save(self.collate(data_list),
> File "/home/user/anaconda3/envs/SOG/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 103, in collate
>     data, slices, _ = collate(
> File "/home/user/anaconda3/envs/SOG/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 84, in collate
>     value, slices, incs = _collate(attr, values, data_list, stores,
> File "/home/user/anaconda3/envs/SOG/lib/python3.7/site-packages/torch_geometric/data/collate.py", line 155, in _collate
>     value = torch.cat(values, dim=cat_dim or 0, out=out)
> RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 106 but got size 102 for tensor number 1 in the list.
> ```

Hello, I guess you have to replace the original "collate.py" in the torch _geometric by using my uploaded "collate.py", i.e., SubOptGraph/collate.py.

**Comment by BlackBoxOP** [comment]
I replaced it, but this error also occurred.

**Comment by Jo3690** [comment]
> I replaced it, but this error also occurred.

Unfortunately,that sounds not so good. You also replaced the "data.py" using the the "/SubOptGraph/data.py"? There used to be a former asker that could run it successfully. Do you install the correct version of packages?

**Comment by BlackBoxOP** [comment]
OK, that works! Thank you so much.

**Comment by Jo3690** [comment]
> OK, that works! Thank you so much.

Got it! No problem.
